# Generated by Django 4.1.1 on 2022-11-18 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_photocomment_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photocomment',
            name='user',
        ),
    ]
